{
 "title": "OpenTelemetry Log4j2 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"opentelemetry-log4j2-alloy\"}"
    }
   ]
  },
  {
   "title": "Log Count by Severity",
   "type": "timeseries",
   "description": "Log count by severity level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(severity) (count_over_time({service_name=\"opentelemetry-log4j2-alloy\"} | unwrap severity [$__interval]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Errors and Exceptions",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"opentelemetry-log4j2-alloy\"} |= `error` or |= `exception`"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"opentelemetry-log4j2-alloy\", severity=\"ERROR\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"opentelemetry-log4j2-alloy\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Log Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(severity) (count_over_time({service_name=\"opentelemetry-log4j2-alloy\"} | unwrap severity [$__range]))",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}